project:
  type: website

website:
  title: "17.831 - Data and Politics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - syllabus.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

