project:
  type: website

website:
  title: "17.831 - Data and Politics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - syllabus.qmd
      - schedule.qmd
      - materials.qmd

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

editor: visual

