---
title: "Syllabus"
---

::: {.columns}

::: {.column width="50%"}
:::: {.course-details}
### Instructor

{{< fa user >}} [F. Daniel Hidalgo](https://www.dhidalgo.me)

{{< fa building >}} E53-402

{{< fa  envelope >}} [dhidalgo@mit.edu](mailto:dhidalgo@mit.edu)

{{< fa calendar >}} [Office Hours](https://fantastical.app/dhidalgo/office-hours)

::::
:::
::: {.column width="50%"}
:::: {.course-details}
### Course Details

{{< fa calendar >}} Tuesdays and Thursdays

{{< fa clock >}} 9:30-11:00am

{{< fa location-dot >}} 56-154 

{{< ai piazza >}} [Piazza](https://piazza.com/mit/spring2024/17831/home)
::::
:::
:::

## Course Objectives

Many of the most pressing social problems have political causes and consequences. Rather than just passively observing these problems, social scientists have developed a range of tools that involve interventions and data collection to understand and address these problems. This course will focus on two essential data-intensive tools for understanding social dynamics: experiments and surveys. Experiments allow us to understand the causal effects of policies and interventions, while surveys allow us to measure difficult-to-observe attitudes and behaviors in a population. This course will provide an introduction to the design and analysis of experiments and surveys through the lens of innovative research in political science and public policy. The course will focus on various substantive [topics](schedule.qmd##topics-overview), including discriminatory attitudes, political participation, combatting voter fraud, and misinformation. Students will analyze actual data and design and field their survey experiment on a chosen topic.

By the end of this course, students will be able to:

-   Describe how experimental and survey methods can be used to understand pressing social problems.
-   Design surveys and experiments that are applicable to a variety of social settings.
-   Use statistical principles to evaluate the quality of survey and experimental designs.
-   Apply statistical models to experimental and survey data.
-   Analyze data using modern statistical computing tools, in particular the statistical programming language `R`.

### Expectations

In this course, you will be expected to:

-   Complete six problem sets.
-   Complete regular reading quizzes. 
-   Complete eight weekly tutorials. 
-   Participate in in-person and online class discussions.
-   Design and implement a survey experiment with a diverse sample.

### Prerequisites

No prerequisites will be assumed.

## Course Structure

The basic cadence of the course will be as follows, though there may be small differences depending on the week:

-   **Monday**: Complete reading, watch course lectures, and complete reading quiz.
-   **Tuesday**: Class meets.
-   **Wednesday**: Complete coding tutorial, submit assignments (if due)
-   **Thursday**: Class meets; assignments are posted

### Class Lectures

Class lectures will be a mix of traditional lectures, in-class activities, and group discussions. In addition to in-class lectures, I may occasionally post a recorded lecture.  During lecture, we will often be working with data and code, so please bring a computer to class, if possible. 

### Tutorials

We will assign short weekly coding tutorials that will assess your knowledge of the class materials and prepare you for the in-class activities. Tutorials will primarily be graded based on completion and not whether the answers are correct. Tutorials will generally be due on Wednesday by 11:59pm ET.

### Problem Sets

Competence at the design and analysis of experiments and surveys requires practice with real world datasets and the design of simulations. For the first 2/3 of the course, I will assign problem sets that will give you the opportunity to practice the methods you learn in the course. The problem sets will often involve the creation of a simulation and/or the analysis of data from an assigned reading. In the second half of the course, substantial parts of the problem set will be devoted to the design of the class project.

I will assign *six* problem sets throughout the semester. They will be due on Thursdays by 11:59pm ET. I encourage students to work in groups, but each student must submit their own assignment. 

::: {.callout-note title="Lowest Homework Grade is Dropped"}
When calculating the overall homework grade, I will drop the lowest homework grade. This is to account for unexpected events that may prevent you from completing an assignment on time.
:::

### Online Forum

We will use [Piazza](https://piazza.com/mit/spring2024/17831/home) for class discussions. If you are having trouble with a question on a problem set or on a reading, please post your question using Piazza. I strongly encourage students to assist in answering questions as they come up. Except under unusual circumstances, it is better to post on Piazza than email me as everyone can benefit from the posted responses. I will monitor Piazza and try to answer within 24 hours. The site is: [https://piazza.com/mit/spring2024/17831/home](https://piazza.com/mit/spring2024/17831/home)

### Grading

The final grade in the course will be based on the following components:

| Category            | Percent of Final Grade |
|---------------------|------------------------|
| Coding Tutorials    | 5%                     |
| Reading Quizzes     | 5%                     |
| Problem Sets        | 50%                    |
| Class Participation | 25%                    |
| Class Project Writeup      | 15%                    |

Class participation is based on participation in class discussions, presentations, and activities, as well as participation in Piazza discussions. 

## Class Project

For the final project, we will collectively design and implement an experiment embedded in a short survey. In the second half of the semester, we will devote time each week to design the survey and experiment. The goal of this project is to give students experience crafting a research design and collecting real data on a question of interest. The data will be collected on US adults through a crowd-sourcing platform.  While we will collectively design the survey and experiment, each student will be responsible for pre-registering their analysis,  analyzing the data and writing up the results on their own.

Students in the class will:

1. Propose a research question.
2. Design an intervention suitable for a survey experiment.
3. Write a questionnaire.
4. Design a sampling plan and analysis strategy sufficient for answering their research question.
5. Pre-register their study.
6. Analyze and write up the results of the study. 


## Course Policies

### Late Policy

For problem sets submitted late, we will deduct 10% of the grade for each day late. Problem sets will not be accepted more than three days after the due date. This penalty will be waived in the case of a documented medical or family emergency.

### Office Hours and Getting Help
I hold regular weekly office hours on Friday afternoons. Please sign up for in-person or zoom office hours at the following link: [https://fantastical.app/dhidalgo/office-hours](https://fantastical.app/dhidalgo/office-hours). 

If you run into problems that you can’t solve on your own, please use the class website on Piazza to post questions. I strongly encourage students to assist in answering questions as they come up. Unless absolutely necessary, it is better to post on Piazza than email me as everyone can benefit from the posted responses. I will monitor Piazza and try to answer within 24 hours.

### AI Tools

The use of generative AI tools such as ChatGPT is allowed for your assignments in this class. However, a central goal of the class is to help you become independent and critical thinkers, so we discourage you from the extensive use of generative AI tools for writing code or answers to problem sets.

If you do use AI-generated content in your assignments, you must clearly indicate what work is yours and what part is AI-generated through proper attribution. We also ask you provide a short one-paragraph summary at the beginning of the assignment on how you used AI tools. 

## Course Materials

### Readings

Almost all readings for the course are available online and linked from the course website in the [schedule](schedule.qmd) page or in each week's [materials page](materials.qmd) page.

The one exception is that you should purchase the following book: 

::: {.callout-warning}
## Required Purchase
Gerber, Alan S., and Donald P. Green. *Field Experiments: Design, Analysis, and Interpretation*.  New York London: W. W. Norton & Company, 2012.
:::

### Computing 

We will use [`R`](https://www.r-project.org/) for all of the data  analysis in this course. `R` is a free, open-source statistical programming language that is widely used in the social sciences. We will use the [`RStudio`](https://www.rstudio.com/) integrated development environment (IDE) to write and execute `R` code. `RStudio` is also free and open-source.

You should install `R` on your own computer, but to forestall any installation problems, we will provide the option to use the Posit Cloud service for the first few weeks of the course. This service allows you to run `R` and `RStudio` in your web browser. This cloud service can be resource constrained, however, so it is strongly recommended that you install `R` and `RStudio` on your own computer as soon as possible.  

